import { Inter } from "next/font/google";
import "./globals.css";
import { ColorSchemeScript, MantineProvider, createTheme } from "@mantine/core";
import '@mantine/core/styles.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AdPulseNetwork",
  description: "Generated by create next app",
};

const theme = createTheme({

});

export default function RootLayout({ children }) {
  return (
    <html lang="en"  data-mantine-color-scheme="light">
      <body className={inter.className}>
      <ColorSchemeScript forceColorScheme="light" />
        <MantineProvider theme={theme} defaultColorScheme="light">
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}